#ifndef TESTS_NATIVE_STUBS_ZF_DRIVER_PWM_H
#define TESTS_NATIVE_STUBS_ZF_DRIVER_PWM_H

#define PWM2_MODULE1_CHA_C8  0
#define PWM2_MODULE1_CHB_C9  1
#define PWM2_MODULE0_CHA_C6  2
#define PWM2_MODULE0_CHB_C7  3
#define PWM2_MODULE3_CHA_D2  4
#define PWM2_MODULE3_CHB_D3  5
#define PWM2_MODULE2_CHA_C10 6
#define PWM2_MODULE2_CHB_C11 7

#endif
